version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"  # Corrected to ensure Dependabot checks the root directory
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.gitpod"
    schedule:
      interval: "weekly"
